### ISSUE TITLE
Incorrect autocorrect for `RSpec/VerifiedDoubleReference`

### ISSUE THREAD

**Issue by ydah** [rubocop/rubocop-rspec#1679] opened 2023-08-02 09:24 UTC
We have following RSpec code:
```ruby
let(:foo_mock) { instance_double('Foo bar') }
```

Run `bundle exec rubocop -A --only RSpec/VerifiedDoubleReference`.
Then it's autocorrected as follows:
```ruby
# before
let(:foo_mock) { instance_double('Foo bar') }

# after
let(:foo_mock) { instance_double(Foo bar) }
```

What should we do if the argument string of instance_double contains spaces?

**Comment by pirj** [comment] 2023-08-03 19:05
My apologies for the late opinion here, @r7kamura @ydah 

This is a duplicate of https://github.com/rubocop/rubocop-rspec/issues/1262 and had been rejected in the past.

**Closed by pirj** 2023-08-03 19:05 UTC
Labels: bug
