### ISSUE TITLE
RSpec/NoExpectationExample raises offense for expect which is called in methods.

### ISSUE THREAD

**Issue by PradipDKshirsagar** [rubocop/rubocop-rspec#1407] opened 2022-10-07 11:07 UTC
RSpec/NoExpectationExample raises offense for expect which is called in methods.
--------
RSpec/NoExpectationExample not working for the spec which has any expect statement in a different method which is called in that it blocks instead of expect statement written in it block itself.

```
file_name:- expection_issue_spec.rb

# frozen_string_literal: true

RSpec.describe ExpectionIssue do
  def addition(first_number, second_number)
    first_number + second_number
  end

  def addition_expect_statement(first_number, second_number)
    expect(addition(first_number, second_number)).to eq 3
  end

  it 'returns addition of provided numbers' do
    addition_expect_statement(1, 2)
  end
end
```

## Expected behavior

Should not get a message `RSpec/NoExpectationExample: No expectation found in this example.`  for a block of code.

## Actual behavior

Getting a message `RSpec/NoExpectationExample: No expectation found in this example.` for a block of code.

## Steps to reproduce the problem
Run the below command to reproduce the issue by creating a file with the above block of code.
`rubocop expection_issue_spec.rb `

## RuboCop version

```
$ rubocop -V
1.36.0 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 3.1.2) [x86_64-darwin20]
  - rubocop-performance 1.15.0
  - rubocop-rails 2.16.1
  - rubocop-rspec 2.13.2
  - rubocop-thread_safety 0.4.4
```

**Comment by pirj** [comment] 2022-10-07 14:59
What is `addition_expect_statement`?

**Comment by pirj** [comment] 2022-10-07 15:18
I intend to close this as a duplicate of #1385. Welcome to the discussion there.

**Closed by pirj** 2022-10-07 15:18 UTC
