### ISSUE TITLE
[RSpec/Capybara/SpecificMatcher] false positive for anchor with attributes

### ISSUE THREAD

**Issue by jcoyne** [rubocop/rubocop-rspec#1369] opened 2022-08-26 16:20 UTC
```
spec/requests/work_edit_button_spec.rb:46:33: C: RSpec/Capybara/SpecificMatcher: Prefer have_link over have_selector.
        expect(rendered).not_to have_selector('a[data-controller="popover"]')
```

However I don't believe there is any way to pass this attribute selector to `have_link`.

**Comment by ydah** [comment] 2022-08-26 21:20
It appears to be a duplicate of https://github.com/rubocop/rubocop-rspec/issues/1327 .
This issue has already been resolved and merged into the master branch (https://github.com/rubocop/rubocop-rspec/pull/1328), so please wait for the next release.

**Comment by jcoyne** [comment] 2022-08-27 00:21
Yes. Definitely a duplicate

**Closed** 2022-08-27 00:21 UTC

**Comment by ydah** [comment] 2022-08-27 00:23
@jcoyne Thanks for the feedback. If you have any more issues, I'd be glad to hear from you via Issue.
