### ISSUE TITLE
Running `rubocop --auto-gen-config` ignores `RSpec/BeforeAfterAll` offense

### ISSUE THREAD

**Issue by mwolman** [rubocop/rubocop-rspec#1335] opened 2022-07-21 03:57 UTC
## Expected behavior

After running `rubocop --auto-gen-config`, all the offenses are added to the `.rubocop_todo.yml` file, and then, if you run `rubocop -a` you should have 0 offenses detected.

## Actual behavior

I ran `rubocop -a` and there's still 1 offense related to the `RSpec/BeforeAfterAll` cop 

## Steps to reproduce the problem

1. In your `rails_helper` file, define something like this:
```ruby
RSpec.configure do |config|
  
  config.before(:all) do
    ...
  end

  config.use_transactional_fixtures = true

end
```

2. Install `rubocop`, `rubocop-rails` and `rubocop-rspec` with the versions mentioned below
3. Run `rubocop --auto-gen-config`
4. Run `rubocop -a`
5. Check that you have 1 offense

## RuboCop version

```
1.7.0 (using Parser 3.1.2.0, rubocop-ast 1.18.0, running on ruby 2.7.6 arm64-darwin21)
  - rubocop-performance 1.5.2
  - rubocop-rails 2.11.3
  - rubocop-rspec 2.4.0
```

**Comment by mwolman** [comment] 2022-07-25 20:14
@pirj I only had 2 offenses in the whole repo, so I'm sure it didn't exceed that number

**Comment by pirj** [comment] 2022-07-25 20:25
Let's double-check if it's a cop deficiency, or it works as designed. May I kindly ask you to run the above command, @mwolman ?

**Comment by pirj** [comment] 2022-07-26 20:54
I'm inclined to close this, as the behaviour seems to be as expected.
Thanks for reporting, this motivated me to check some gen-config related code and docs.

**Closed by pirj** 2022-07-26 20:54 UTC
